// ==========================================
// 本地端可自行調整的儀表板設定
// ==========================================
window.LOCAL_DASHBOARD_CONFIG = {
    view: {
        hideSourceId: true,
        tablePreviewLimit: 200,
        preferredMetricKeywords: [
            "Vol (V)",
            "Temp",
            "PWR 5V (V)",
            "PWR 3V (V)",
            "Cur (mA)",
            "ADCS_TMP",
            "MAG_X",
            "RATE (deg/s)_X",
            "FSS_STAT_Act" // 新增讓 FSS 狀態容易被選到
        ],
        preferredMetricKeywordsByCategory: {
            "EPS Beacon": ["Vol (V)", "Cur (mA)", "Energy (Wh)", "Temp (°C)", "PWR 5V (V)", "PWR 3V (V)"],
            "ADCS 1 Beacon": ["PWR 5V (V)", "PWR 3V (V)", "HERR", "MODE", "LLA_ALT"],
            "ADCS 2 Beacon": ["ADCS_TMP (°C)", "FSS_TMP_0_Top (°C)", "FSS_TMP_0_Bottom (°C)", "ATT_ERR_RATE (deg/s)_X", "MAG_X", "SV_X"],
            "ADCS 3 HIL Beacon": ["IMU_B (deg/s)_X", "IMU_B (deg/s)_Y", "MTQ_X", "MAG_B_X", "FSS_STAT_Act", "CMG_STAT_0"],
            "OBC RST Beacon": ["LOW_VOLTAGE_SHUTDOWN_ADCS (V)", "LOW_VOLTAGE_TARGET_TRACKING (V)", "DETUMBLE_ANGULAR_RATE_THRESHOLD_DPS"]
        }
    },
    range: {
        yMin: null,
        yMax: null,
        timeStart: "",
        timeEnd: ""
    },
    rangeByMetric: {
        "Vol (V)": { yMin: 14.0, yMax: 16.2 },
        "Temp (°C)": { yMin: -40, yMax: 90 },
        "PWR 5V (V)": { yMin: 4.7, yMax: 5.3 },
        "PWR 3V (V)": { yMin: 3.0, yMax: 3.6 },
        "Cur (mA)": { yMin: -1500, yMax: 2000 }
    },
    rangeByCategory: {
        "EPS Beacon": {
            "__all__": { yMin: null, yMax: null, timeStart: "", timeEnd: "" },
            "來源ID": { yMin: null, yMax: null },
            "網站時間(UTC)": { yMin: null, yMax: null },
            "封包時間(UTC)": { yMin: null, yMax: null },
            "MODE": { yMin: -1, yMax: 8 },
            "Sat_mode": { yMin: -1, yMax: 8 },
            "LVLH": { yMin: -0.2, yMax: 1.2 },
            "Outputs Mask": { yMin: 0, yMax: 70000 },
            "Callsign": { yMin: null, yMax: null },
            "Energy (Wh)": { yMin: 30, yMax: 70 },
            "Vol (V)": { yMin: null, yMax: null },
            "Cur (mA)": { yMin: null, yMax: null },
            "Temp (°C)": { yMin: -10, yMax: 20 },
            "12V (V)": { yMin: 0, yMax: 13 },
            "12V (mA)": { yMin: 0, yMax: 300 },
            "12V (mW)": { yMin: 0, yMax: 2000 },
            "5V_1 (V)": { yMin: 0, yMax: 6 },
            "5V_1 (mA)": { yMin: 0, yMax: 500 },
            "5V_1 (mW)": { yMin: 0, yMax: 2000 },
            "5V_2 (V)": { yMin: 0, yMax: 6 },
            "5V_2 (mA)": { yMin: 0, yMax: 500 },
            "5V_2 (mW)": { yMin: 0, yMax: 2000 },
            "3V3_1 (V)": { yMin: 0, yMax: 4 },
            "3V3_1 (mA)": { yMin: 0, yMax: 500 },
            "3V3_1 (mW)": { yMin: 0, yMax: 2000 },
            "3V3_2 (V)": { yMin: 0, yMax: 4 },
            "3V3_2 (mA)": { yMin: 0, yMax: 500 },
            "3V3_2 (mW)": { yMin: 0, yMax: 2000 }
        },
        "ADCS 1 Beacon": {
            "__all__": { yMin: null, yMax: null, timeStart: "", timeEnd: "" },
            "來源ID": { yMin: null, yMax: null },
            "網站時間(UTC)": { yMin: null, yMax: null },
            "封包時間(UTC)": { yMin: null, yMax: null },
            "MODE": { yMin: 0, yMax: 6 },
            "HERR": { yMin: -0.2, yMax: 1.2 },
            "SERR": { yMin: -0.2, yMax: 1.2 },
            "WDT": { yMin: -0.2, yMax: 1.2 },
            "UV": { yMin: -0.2, yMax: 1.2 },
            "OC": { yMin: -0.2, yMax: 1.2 },
            "OT": { yMin: -0.2, yMax: 1.2 },
            "GNSS": { yMin: -0.2, yMax: 1.2 },
            "ADV": { yMin: -1, yMax: 3 },
            "TLE": { yMin: -0.2, yMax: 1.2 },
            "DES": { yMin: -0.2, yMax: 1.2 },
            "SUN": { yMin: -0.2, yMax: 1.2 },
            "TGL": { yMin: -0.2, yMax: 1.2 },
            "TUMB": { yMin: -0.2, yMax: 1.2 },
            "AME": { yMin: -0.2, yMax: 1.2 },
            "CUSSV": { yMin: -0.2, yMax: 1.2 },
            "EKF": { yMin: -0.2, yMax: 1.2 },
            "ACT_ERR_CMG": { yMin: 0, yMax: null },
            "ACT_ERR_MTQ": { yMin: 0, yMax: null },
            "ACT_ERR_RAW": { yMin: 0, yMax: null },
            "SEN_ERR_FSS": { yMin: 0, yMax: null },
            "SEN_ERR_MAG": { yMin: 0, yMax: null },
            "SEN_ERR_IMU": { yMin: 0, yMax: null },
            "SEN_ERR_STR": { yMin: 0, yMax: null },
            "CSS_ERR": { yMin: 0, yMax: null },
            "Q": { yMin: null, yMax: null },
            "LLA": { yMin: null, yMax: null },
            "V": { yMin: 0, yMax: 5 },
            "PWR 3V": { yMin: 0, yMax: null },
            "LLA_LAT": { yMin: -180, yMax: 180 },
            "LLA_LON": { yMin: -180, yMax: 180 },
            "LLA_ALT": { yMin: 0, yMax: 600000 },
            "RATE (raw rad/s)_X": { yMin: -1, yMax: 1 },
            "RATE (raw rad/s)_Y": { yMin: -1, yMax: 1 },
            "RATE (raw rad/s)_Z": { yMin: -1, yMax: 1 },
            "RATE (deg/s)_X": { yMin: -1, yMax: 1 },
            "RATE (deg/s)_Y": { yMin: -1, yMax: 1 },
            "RATE (deg/s)_Z": { yMin: -1, yMax: 1 },
            "PWR 5V (V)": { yMin: 0, yMax: null },
            "PWR 5V (mA)": { yMin: 0, yMax: 300 },
            "PWR 3V (V)": { yMin: 0, yMax: null },
            "PWR 3V (mA)": { yMin: 0, yMax: 300 }
        },
        "ADCS 2 Beacon": {
            "__all__": { yMin: null, yMax: null, timeStart: "", timeEnd: "" },
            "來源ID": { yMin: null, yMax: null },
            "網站時間(UTC)": { yMin: null, yMax: null },
            "CMG_TMP_0_Top (°C)": { yMin: -10, yMax: 50 },
            "CMG_TMP_0_Bottom (°C)": { yMin: -10, yMax: 50 },
            "CMG_TMP_1_Top (°C)": { yMin: -10, yMax: 50 },
            "CMG_TMP_1_Bottom (°C)": { yMin: -10, yMax: 50 },
            "CMG_TMP_2_Top (°C)": { yMin: -10, yMax: 50 },
            "CMG_TMP_2_Bottom (°C)": { yMin: -10, yMax: 50 },
            "CMG_TMP_3_Top (°C)": { yMin: -10, yMax: 50 },
            "CMG_TMP_3_Bottom (°C)": { yMin: -10, yMax: 50 },
            "Callsign": { yMin: null, yMax: null },
            "ATT_ERROR_X": { yMin: -1, yMax: 1 },
            "ATT_ERROR_Y": { yMin: -1, yMax: 1 },
            "ATT_ERROR_Z": { yMin: -1, yMax: 1 },
            "ATT_ERR_RATE (raw rad/s)_X": { yMin: -1, yMax: 1 },
            "ATT_ERR_RATE (raw rad/s)_Y": { yMin: -1, yMax: 1 },
            "ATT_ERR_RATE (raw rad/s)_Z": { yMin: -1, yMax: 1 },
            "ATT_ERR_RATE (deg/s)_X": { yMin: -10, yMax: 10 },
            "ATT_ERR_RATE (deg/s)_Y": { yMin: -10, yMax: 10 },
            "ATT_ERR_RATE (deg/s)_Z": { yMin: -10, yMax: 10 },
            "SV_X": { yMin: 0, yMax: 1 },
            "SV_Y": { yMin: 0, yMax: 1 },
            "SV_Z": { yMin: 0, yMax: 1 },
            "MAG_X": { yMin: -100, yMax: 100 },
            "MAG_Y": { yMin: -100, yMax: 100 },
            "MAG_Z": { yMin: -100, yMax: 100 },
            "ADCS_TMP (°C)": { yMin: -10, yMax: 30 },
            "FSS_TMP_0 (°C)": { yMin: -10, yMax: 50 },
            "FSS_TMP_1 (°C)": { yMin: -10, yMax: 50 },
            "FSS_TMP_2 (°C)": { yMin: -10, yMax: 50 },
            "FSS_TMP_3 (°C)": { yMin: -10, yMax: 50 },
            "FSS_TMP_4 (°C)": { yMin: -10, yMax: 50 },
            "FSS_TMP_5 (°C)": { yMin: -10, yMax: 50 }
        },
        "ADCS 3 HIL Beacon": {
            "__all__": { yMin: null, yMax: null, timeStart: "", timeEnd: "" },
            "來源ID": { yMin: null, yMax: null },
            "網站時間(UTC)": { yMin: null, yMax: null },
            "FSS_STAT_Inst": { yMin: 0, yMax: null },
            "FSS_STAT_Act": { yMin: 0, yMax: null },
            "FSS_STAT_Flt": { yMin: 0, yMax: null },
            "CMG_STAT_0": { yMin: 0, yMax: 3 },
            "CMG_STAT_1": { yMin: 0, yMax: 3 },
            "MTQ_X": { yMin: 0, yMax: null },
            "MTQ_Y": { yMin: 0, yMax: null },
            "MTQ_Z": { yMin: 0, yMax: null },
            "MAG_B_X": { yMin: -100, yMax: 100 },
            "MAG_B_Y": { yMin: -100, yMax: 100 },
            "MAG_B_Z": { yMin: -100, yMax: 100 },
            "IMU_B (raw rad/s)_X": { yMin: -0.1, yMax: 0.1 },
            "IMU_B (raw rad/s)_Y": { yMin: -0.1, yMax: 0.1 },
            "IMU_B (raw rad/s)_Z": { yMin: -0.1, yMax: 0.1 },
            "IMU_B (deg/s)_X": { yMin: -5, yMax: 5 },
            "IMU_B (deg/s)_Y": { yMin: -5, yMax: 5 },
            "IMU_B (deg/s)_Z": { yMin: -5, yMax: 5 },
            "MAG_S_X": { yMin: -100, yMax: 100 },
            "MAG_S_Y": { yMin: -100, yMax: 100 },
            "MAG_S_Z": { yMin: -100, yMax: 100 }
        },
        "OBC RST Beacon": {
            "__all__": { yMin: null, yMax: null, timeStart: "", timeEnd: "" },
            "來源ID": { yMin: null, yMax: null },
            "網站時間(UTC)": { yMin: null, yMax: null },
            "RST_WWD": { yMin: 0, yMax: 300 },
            "RST_IWD": { yMin: 0, yMax: 300 },
            "RST_LPR": { yMin: 0, yMax: 300 },
            "RST_POR": { yMin: 0, yMax: 300 },
            "RST_RstPin": { yMin: 0, yMax: 300 },
            "RST_BOR": { yMin: 0, yMax: 300 },
            "RST_HardFault": { yMin: 0, yMax: 300 },
            "RST_MemFault": { yMin: 0, yMax: 300 },
            "RST_BusFault": { yMin: 0, yMax: 300 },
            "RST_UsageFault": { yMin: 0, yMax: 300 },
            "DETUMBLE_ANGULAR_RATE_THRESHOLD_DPS": { yMin: 0, yMax: 2 },
            "Callsign": { yMin: null, yMax: null },
            "LOW_VOLTAGE_SHUTDOWN_ADCS (V)": { yMin: 14, yMax: 16 },
            "LOW_VOLTAGE_OPEN_ADCS (V)": { yMin: 14, yMax: 16 },
            "LOW_VOLTAGE_ENTER_SAFE_MODE_MV (V)": { yMin: 14, yMax: 16 },
            "LOW_VOLTAGE_EXIT_SAFE_MODE_MV (V)": { yMin: 14, yMax: 16 },
            "LOW_VOLTAGE_TARGET_TRACKING (V)": { yMin: 14, yMax: 16 },
            "DETUMBLE_ANGULAR_RATE_THRESHOLD_DPS (°/s)": { yMin: 0, yMax: 2 }
        }
    },
    valueFiltersByCategory: {
        "EPS Beacon": {
            "Outputs Mask": {
                mode: "bitmask",
                applyToAllMetrics: false,
                allowedValues: [65313, 32801],
                requiredBitPowers: [15, 5, 0],
                allowedBitPowers: [15, 14, 13, 12, 11, 10, 9, 8, 5, 0],
                allowCombinations: true,
                minValue: 0,
                maxValue: 70000
            }
        }
    },
    spikeFilter: {
        enabled: false,
        minSeriesPoints: 6,
        iqrQ1: 0.25,
        iqrQ3: 0.75,
        iqrK: 3.0,
        minAfterIqrPoints: 6,
        madK: 6.0,
        fallbackMultiplier: 4.0,
        requireSignFlip: true
    }
};